### ISSUE TITLE
SIGABRT in matrix_e2e_handle_sync_key_counts

### ISSUE THREAD

**Issue by brianjmurrell** [matrix-org/purple-matrix#98]
Could be a duplicate of #95.

```
Thread 1 (Thread 0x7ff7ebee1c80 (LWP 4896)):
#0  0x00007ff7ed3aaeb5 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {1024, 140737052832848, 140702815290368, 140702813887336, 32, 356482285568, 1, 206158430216, 140737052832784, 140737052832576, 18446744073709551615, 206158430216, 140737052832784, 140737052832592, 140701652429648, 140698833649749}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ff7ed395895 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fffe60a6ec4, sa_sigaction = 0x7fffe60a6ec4}, sa_mask = {__val = {502, 140702815307424, 94769428710544, 140702815290176, 502, 502, 140702813980190, 94769469947840, 140702815307424, 94769428710544, 502, 140702815290176, 94769454520512, 7598263483120643695, 140702813932099, 368}}, sa_flags = 0, sa_restorer = 0x56313b476030}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000563138d95d40 in sighandler (sig=<optimized out>) at gtkmain.c:179
        written = <optimized out>
#3  0x0000563138d95d40 in sighandler (sig=<optimized out>) at gtkmain.c:162
        written = <optimized out>
#4  0x00007ff7ed54de70 in <signal handler called> () at /lib64/libpthread.so.0
#5  0x00007ff7e4e57675 in matrix_e2e_handle_sync_key_counts (pc=<optimized out>, count_object=0x7ff7a8032b50, force_send=0) at matrix-e2e.c:937
        need_to_send = 0
        valid_counts = 0
        conn = 0x697274616d3a6e6f
        max_keys = <optimized out>
        to_create = <optimized out>
        __func__ = "matrix_e2e_handle_sync_key_counts"
#6  0x00007ff7e4e5577f in matrix_api_complete (url_data=<optimized out>, user_data=0x56313b476030, ret_data=<optimized out>, ret_len=<optimized out>, error_message=0x0) at matrix-api.c:330
        data = 0x56313b476030
        response_data = 0x56313b97d180
        response_code = 200
        root = 0x56313bac18c0
#7  0x00007ff7eda77ca5 in url_fetch_recv_cb (url_data=0x56313cb62600, source=<optimized out>, cond=<optimized out>) at util.c:3996
        gfud = 0x56313cb62600
        len = <optimized out>
        buf = "\nCache-Control: no-store, must-revalidate, no-cache\r\nPragma: no-cache\r\nContent-Length: 553\r\nContent-Type: application/json; charset=utf-8\r\nContent-Encoding: gzip\r\nX-Content-Type-Options: nosniff\r\n\000\000\000\000"...
        data_cursor = <optimized out>
        got_eof = <optimized out>
        __func__ = "url_fetch_recv_cb"
#8  0x0000563138d7cb86 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x56313b9438d0) at gtkeventloop.c:73
        closure = 0x56313b9438d0
        purple_cond = PURPLE_INPUT_READ
#9  0x00007ff7ed6f1edd in g_main_dispatch (context=0x56313a2266e0) at ../glib/gmain.c:3189
        dispatch = <optimized out>
        prev_source = 0x0
        was_in_call = <optimized out>
        user_data = 0x56313b9438d0
        callback = 0x563138d7cb50 <pidgin_io_invoke>
        cb_funcs = 0x7ff7ed7c4280 <g_source_callback_funcs>
        cb_data = 0x56313bc5a220
        need_destroy = <optimized out>
        source = 0x56313be242e0
        current = 0x56313a4507b0
        i = 0
        __FUNCTION__ = "g_main_dispatch"
#10 0x00007ff7ed6f1edd in g_main_context_dispatch (context=context@entry=0x56313a2266e0) at ../glib/gmain.c:3854
#11 0x00007ff7ed6f2270 in g_main_context_iterate (context=0x56313a2266e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927
        max_priority = 2147483647
        timeout = 2134
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x56313bafcea0
#12 0x00007ff7ed6f25a3 in g_main_loop_run (loop=0x56313b55f4e0) at ../glib/gmain.c:4123
        __FUNCTION__ = "g_main_loop_run"
#13 0x00007ff7edeee042 in IA__gtk_main () at gtkmain.c:1270
        tmp_list = 0x0
        functions = 0x0
        init = <optimized out>
        loop = 0x56313b55f4e0
#14 0x0000563138d41b50 in main (argc=<optimized out>, argv=<optimized out>) at gtkmain.c:939
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = <optimized out>
        opt_si = <optimized out>
        opt_config_dir_arg = 0x0
        opt_login_arg = 0x0
        opt_session_arg = 0x0
        search_path = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {91142, 0 <repeats 15 times>}}
        errmsg = '\000' <repeats 1320 times>...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        segfault_message_tmp = <optimized out>
        error = 0x0
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        migration_failed = 0
        active_accounts = <optimized out>
        long_options = {{name = 0x563138de1cb1 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x563138dcff79 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x563138dddcbb "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x563138dd1ac3 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x563138dddb65 "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x563138dddcc8 "multiple", has_arg = 0, flag = 0x0, val = 109}, {name = 0x563138dddcd1 "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x563138de1ca7 "session", has_arg = 1, flag = 0x0, val = 115}, {name = 0x563138dd421d "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x563138de1cba "display", has_arg = 1, flag = 0x0, val = 68}, {name = 0x563138dde7aa "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}

Thread 2 (Thread 0x7ff7da210700 (LWP 4934)):
#0  0x00007ff7ed4633f7 in __GI___poll (fds=0x56313ab6a620, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ff7ed6f21de in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x56313ab6a620, timeout=<optimized out>, context=0x56313ad41200) at ../glib/gmain.c:4228
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7ff7ed701d50 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x56313ab6a620
#2  0x00007ff7ed6f21de in g_main_context_iterate (context=context@entry=0x56313ad41200, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3922
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x56313ab6a620
#3  0x00007ff7ed6f2313 in g_main_context_iteration (context=0x56313ad41200, may_block=may_block@entry=1) at ../glib/gmain.c:3988
        retval = <optimized out>
#4  0x00007ff7ed6f2361 in glib_worker_main (data=<optimized out>) at ../glib/gmain.c:5868
#5  0x00007ff7ed71b4e2 in g_thread_proxy (data=0x56313a76d0f0) at ../glib/gthread.c:805
        thread = 0x56313a76d0f0
        __FUNCTION__ = "g_thread_proxy"
#6  0x00007ff7ed5435a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140702493247232, -8371785846084154035, 140737052834974, 140737052834975, 140737052835120, 140702493244032, 8376349377878478157, 8376320959807802701}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007ff7ed46e163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ff7d9a0f700 (LWP 4935)):
#0  0x00007ff7ed4633f7 in __GI___poll (fds=0x56313ab602b0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ff7ed6f21de in g_main_context_poll (priority=<optimized out>, n_fds=3, fds=0x56313ab602b0, timeout=<optimized out>, context=0x56313a450520) at ../glib/gmain.c:4228
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7ff7ed701d50 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = <optimized out>
        fds = 0x56313ab602b0
#2  0x00007ff7ed6f21de in g_main_context_iterate (context=0x56313a450520, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3922
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = <optimized out>
        fds = 0x56313ab602b0
#3  0x00007ff7ed6f25a3 in g_main_loop_run (loop=0x56313a450610) at ../glib/gmain.c:4123
        __FUNCTION__ = "g_main_loop_run"
#4  0x00007ff7ed252d8a in gdbus_shared_thread_func (user_data=0x56313ad40930) at ../gio/gdbusprivate.c:275
        data = 0x56313ad40930
#5  0x00007ff7ed71b4e2 in g_thread_proxy (data=0x56313a76d190) at ../glib/gthread.c:805
        thread = 0x56313a76d190
        __FUNCTION__ = "g_thread_proxy"
#6  0x00007ff7ed5435a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140702484854528, -8371785846084154035, 140737052835390, 140737052835391, 140737052835536, 140702484851328, 8376346079880465741, 8376320959807802701}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007ff7ed46e163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ff7d880d700 (LWP 4948)):
#0  0x00007ff7ed4633f7 in __GI___poll (fds=fds@entry=0x7ff7c80027e0, nfds=nfds@entry=3, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ff7d3c36cc6 in poll (__timeout=-1, __nfds=3, __fds=0x7ff7c80027e0) at /usr/include/bits/poll2.h:46
        mutex = 0x56313b58d8a0
        r = <optimized out>
        __func__ = "poll_func"
        __PRETTY_FUNCTION__ = "poll_func"
#2  0x00007ff7d3c36cc6 in poll_func (ufds=0x7ff7c80027e0, nfds=3, timeout=-1, userdata=0x56313b58d8a0) at pulse/thread-mainloop.c:69
        mutex = 0x56313b58d8a0
        r = <optimized out>
        __func__ = "poll_func"
        __PRETTY_FUNCTION__ = "poll_func"
#3  0x00007ff7d3c281f8 in pa_mainloop_poll (m=m@entry=0x56313b589410) at pulse/mainloop.c:824
        __func__ = "pa_mainloop_poll"
        __PRETTY_FUNCTION__ = "pa_mainloop_poll"
#4  0x00007ff7d3c28863 in pa_mainloop_iterate (m=0x56313b589410, block=<optimized out>, retval=0x0) at pulse/mainloop.c:926
        r = 0
        __func__ = "pa_mainloop_iterate"
        __PRETTY_FUNCTION__ = "pa_mainloop_iterate"
#5  0x00007ff7d3c28910 in pa_mainloop_run (m=0x56313b589410, retval=retval@entry=0x0) at pulse/mainloop.c:945
        r = <optimized out>
#6  0x00007ff7d3c36c0d in thread (userdata=0x56313b58d860) at pulse/thread-mainloop.c:100
        m = 0x56313b58d860
        mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
        prev_mask = {__val = {0, 110448, 140702189092896, 2032, 140702815323920, 140702189117584, 0, 39, 140702189095712, 94769428551280, 140702815449960, 140702817442016, 39, 140702817993792, 140702189095712, 140702813999011}}
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 94769430707008, 140702390475440, 4097, 0, 0, 0, 0, 140702813999011, 140702189097904, 140702189092992, 140702390473056, 32, 140702189092896, 128, 2032}}, sa_flags = 0, sa_restorer = 0x0}
#7  0x00007ff7d3bd1d0c in internal_thread_func (userdata=0x56313b58da90) at pulsecore/thread-posix.c:81
        t = 0x56313b58da90
        __func__ = "internal_thread_func"
        __PRETTY_FUNCTION__ = "internal_thread_func"
#8  0x00007ff7ed5435a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140702465971968, -8371785846084154035, 140737052836638, 140737052836639, 140737052836640, 140702465968768, 8376343607053045069, 8376320959807802701}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007ff7ed46e163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by penguin42** [comment]
Yeh I think this is the same as #95
